## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [2]:
def share_bread(N, K):
    # Вычисление количества кусков на человека
    x = K // N
    # Вычисление оставшихся кусков
    y = K % N
    return x, y

In [3]:
# Проверка
assert share_bread(N=3, K=14) == (4, 2)

In [4]:
share_bread(N=3, K=14)

(4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [5]:
def leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return 'YOU SHALL PASS'
    else:
        return 'YOU SHALL NOT PASS'

In [6]:
# Проверка
assert leap_year(5) == 'YOU SHALL NOT PASS'
assert leap_year(2000) == 'YOU SHALL PASS'

In [7]:
leap_year(2000) 

'YOU SHALL PASS'

In [8]:
leap_year(5)

'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [9]:
import math

def amulet_area(a, b, c):
    s = (a + b + c) / 2  # Полупериметр
    S = math.sqrt(s * (s - a) * (s - b) * (s - c))  # Формула Герона
    return S

In [10]:
# Проверка
assert amulet_area(3, 4, 5) == 6

In [11]:
amulet_area(3, 4, 5)

6.0

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [12]:
import numpy as np

def cal_euclidean(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

def cal_manhattan(a, b):
    return np.sum(np.abs(a - b))

def cal_cosine(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [13]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

25.199206336708304
65
-0.25282424700798783


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [14]:
my_array = np.random.randint(-10, 10, size=20)  # Генерация массива из 20 случайных чисел
print(np.max(my_array), np.min(my_array))
print(my_array)

9 -9
[-9  5  1  1 -8 -3 -4 -9 -1 -7  3 -4  9 -4  9  7 -3  9  6 -7]


Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [15]:
my_array = np.random.randint(-10, 10, size=(5, 5))  # Матрица 5x5
selected_column = my_array[:, 2]  # Выбор 3-го столбца
print('Shape: ', my_array.shape)
print('Array')
print(my_array)
print('Selected column:', selected_column)

Shape:  (5, 5)
Array
[[  2  -4   6  -3   8]
 [  6   9   0   2   6]
 [ -5  -7   7  -8  -7]
 [  6  -2  -3  -9  -6]
 [ -9 -10  -9  -7  -8]]
Selected column: [ 6  0  7 -3 -9]


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [16]:
def get_unique_rows(X):
    # Используем numpy для получения уникальных строк
    return np.unique(X, axis=0)

In [17]:
X = np.random.randint(4, 6, size=(10,3))
print("Original matrix:")
print(X)

Original matrix:
[[4 5 4]
 [4 5 4]
 [4 5 4]
 [5 4 5]
 [4 4 4]
 [4 5 5]
 [4 4 4]
 [4 5 4]
 [4 4 5]
 [4 4 5]]


In [18]:
print("Unique rows:")
print(get_unique_rows(X))

Unique rows:
[[4 4 4]
 [4 4 5]
 [4 5 4]
 [4 5 5]
 [5 4 5]]
